package pojos;
// Generated 22-feb-2018 17:24:00 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
@SuppressWarnings("serial")
public class Clients implements java.io.Serializable {

	private Integer idClient;
	private String nom;
	private String cognoms;
	private String telefon;
	private String correu;
	private Set<Assistencies> assistencieses = new HashSet<Assistencies>(0);

	public Clients() {
	}

	public Clients(String nom, String cognoms, String telefon) {
		this.nom = nom;
		this.cognoms = cognoms;
		this.telefon = telefon;
	}



	public Clients(String nom, String cognoms, String telefon, String correu) {
		super();
		this.nom = nom;
		this.cognoms = cognoms;
		this.telefon = telefon;
		this.correu = correu;
	}

	public Clients(String nom, String cognoms, String telefon, String correu, Set<Assistencies> assistencieses) {
		this.nom = nom;
		this.cognoms = cognoms;
		this.telefon = telefon;
		this.correu = correu;
		this.assistencieses = assistencieses;
	}


	/**
	 * Afegeixo un constructor nou per que al fer el update al ser client que te autoincrement t'agafi el id
	 * @param idClient
	 * @param nom
	 * @param cognoms
	 * @param telefon
	 * @param correu
	 */
	public Clients(Integer idClient, String nom, String cognoms, String telefon, String correu) {
		super();
		this.idClient = idClient;
		this.nom = nom;
		this.cognoms = cognoms;
		this.telefon = telefon;
		this.correu = correu;
	}

	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCognoms() {
		return this.cognoms;
	}

	public void setCognoms(String cognoms) {
		this.cognoms = cognoms;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public String getCorreu() {
		return this.correu;
	}

	public void setCorreu(String correu) {
		this.correu = correu;
	}

	public Set<Assistencies> getAssistencieses() {
		return this.assistencieses;
	}

	public void setAssistencieses(Set<Assistencies> assistencieses) {
		this.assistencieses = assistencieses;
	}

}
